### ISSUE TITLE
Proposition de nouvelles slides à compiler pour améliorer le tuto

### ISSUE THREAD

**Issue by cecilaki** [SylvainLapoix/Xaringan_squared#8]
---
title: "Xaringan²"
subtitle: "R x Markdown x Github"
author: "Sylvain Lapoix - Datactivist"
date: "Estate 2019"
output:
  SlidesDatactivist::moon_reader:
    css: [default, datactivist, datactivist-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: "macros.js"
params:
  event: Un Xaringan sur Xaringan
  slug: xaringan_squared

---

layout: true
  

`r paste0("<div class='my-footer'><span>", params$event, "</span> <center><div class=logo><img src='https://github.com/datactivist/slides_datactivist/raw/master/inst/rmarkdown/templates/xaringan/resources/img/fond_noir_monochrome.png' width='100px'></center></span></div>")`

---

class: center, middle

Ces slides en ligne : `r paste0("https://sylvainlapoix.github.io/", params$slug)`

Sources : `r paste0("https://github.com/sylvainlapoix/", params$slug)`

Of course, les productions de Datactivist sont librement réutilisables selon les termes de la licence [Creative Commons 4.0 BY-SA](https://creativecommons.org/licenses/by-sa/4.0/legalcode.fr).

<BR>
<BR>

![](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png)
---

background-image: url(https://media.giphy.com/media/26gJztRCkcW8meI3C/giphy.gif)
class: center, top, inverse
# 0. Choisir Xaringan ?

---

# Préambule

**Le choix du support de présentation** est une vraie question chez .red[Datactivist] : "faire des slides" représente en effet une certaine partie de notre activité. Nous sommes consultant.e.s, nous faisons des slides pour tout : 

* Certaines réponses aux appels d'offre
* Animation de réunions
* Animation d'ateliers
* Animation de formations
* On fait même des slides pour expliquer comment faire des slides

---

# Quel support .red[pour quel usage ?]

Comme souvent, **il y a deux écoles**. Datactivist n'échappe pas à la règle des divergences d'opinions, et c'est tant mieux ! Les (nombreuses) discussions internes ont permis de distinguer au moins deux usages principaux : 

.pull-left[

### Les présentations qui ont vocation à être **publiques, publiées et communiquées**

Pour celles-ci, on a souvent et longtemps utilisé Google Slides (*et parfois, on continue*) mais **typiquement pour les formations** où il est souvent demandé de partager le support avec les participant.e.s, avoir une URL simple (et brandée!) à donner plutôt qu'un lourd document .pdf à envoyer par mail, s'est révélé très efficace.

Et pour cela, un outil s'est révélé étonnament créatif en la matière : R ! 

]

.pull-right[

### Les autres

Dans ce cas, on continue d'utiliser les outils dits "classiques" : Powerpoint, Google Slides, PDF. Et c'est aussi souvent très pratique! 

]

---

# Deux écoles ? .red[Mais lesquelles ?]

Tout étant une question d'usage personnel, de familiarité avec certains outils et aussi de façons de penser et de créer, on distingue d'une part : 

* Ceux et celles qui trouvent plus facile et plus simple de créer des slides en codant en Markdown. Cela les aide à se concentrer sur la rédaction du contenu plutôt que sur la mise en forme qui est parfois très chronophage
* Ceux et celles qui préfèrent manipuler des formes, des objets et des couleurs pour faire exposer des idées. 

---

### Intro à Xaringan
.red[[Xaringan](https://github.com/yihui/xaringan)] est un package R développé par Yihui Xie permettant d'utiliser les fonctionnalités de l'outil de présentation Javascript [remark.js](https://remarkjs.com/) dans R et d'y ajouter les spécificités de ce langage (sortie console, dataviz, etc.). Son nom est inspiré de celui [d'un dōjutsu de Naruto](https://naruto.fandom.com/fr/wiki/Sharingan) disposant de deux capacités :
1. *"l'œil de la perspicacité"* ;
2. *"l'œil de l'hypnose"*.

Je ne vous souhaite rien de moins avec vos prez.

#### Atouts (par rapport à un outil de prez classique)
* lisibilité : Markdown + R (et un tout petit peu de CSS si on veut) ;
* versatilité : texte, graph, images, URLs, code R, HTML, Javascript ou CSS en entrée et, en sortie, HTML, PDF, Bar Mitsvah ... ;
* reproductibilité : chaque prez repose sur un simple .Rmd accompagné de fichiers sources permettant de reproduire, réutiliser et adapter.

--

**Et on peut y mettre des GIFs.**

---

# Quels sont les inconvénients .red[et les avantages des 2 méthodes ?]

.pull-left[

### Concevoir des slides en R 

* Permet de les rendre publiques sur le Github de Datactivist avec une URL facile à retenir au nom du répertoire/projet  
* Demande une prise en main technique minimale, avec l'utilisation d'outils et de langage informatique specifique.

]

.pull-right[

### Concevoir des slides manuellement

* Permet de soigner plus précisément le style de ses présentations
* Permet de travailler sur plusieurs modèles de slides différents basés sur le template Datactivist
* Permet d'être très très créatif
* Vous avez réalisé des slides avec PPT toute votre vie, vous en connaissez les avantages et les inconvénients :smile_cat: 

]

---

# Quels sont les prérequis .red[pour utiliser Xaringan ?]

### 1 - Avoir un compte Github

Et bien retenir son pseudo et son mot de passe

### 2 - Savoir structurer un texte et rédiger en Markdown  
Plusieurs tutos existent en plus des slides qui vont suivre. On peut signaler [ce cours d'Open Classroom](https://openclassrooms.com/fr/courses/1304236-redigez-en-markdown) ou celui-ci également [en Français plus centré](https://github.com/luong-komorebi/Markdown-Tutorial/blob/master/README_fr.md) sur Github. 

### 3 - Apprendre à utiliser Rstudio

Vous pouvez créer un compte ici : [rstudio.cloud/datactivist](https://rstudio.cloud/spaces/60104/project/1088506)

### 4 - Savoir se servir d'un terminal

:computer: Et de quelques commandes de bases 

##### Enregistrer son compte et son nom

```
git config --global user.email "ton@adresse.com"
git config --global user.name "Ton nom"
```

### 5 - Savoir puller, commiter, pusher

---

# Lexique utile

* Le **repository** (“dépôt” en français) : il s’agit du dossier ou encoe de l’espace de stockage sur lequel sont les fichiers de votre projet
* **Push** (pousser) : lorsque vous envoyez des fichiers sur le serveur, vous faites un “push”
* **Pull** (tirer) : lorsque vous téléchargez la dernière version des fichiers à partir du serveur, vous faites un “pull”
* **Commit** (valider) : valider des modifications avant de les envoyer au serveur

---

background-image: url(https://media.giphy.com/media/l0Hlxht5Nq8683Sz6/giphy.gif)
class: center, top, inverse

# 1. Créer une présentation

---

### Installer les outils nécessaires

L'interface la plus naturelle pour utiliser Xaringan est [Rstudio](https://www.rstudio.com/) (qui permet notamment de gérer les fichiers et le git).

Xaringan dépend de plusieurs packages courants (Rcpp, markdown, stringr ou encore htmltools). Si vous avez installé le tidyverse, vous en êtes déjà équipé·e·s (mais bon [installez-le quand même](https://www.tidyverse.org/), ça ne pourra que vous servir).

Une fois ces précautions prises, vous pouvez lancer l'installation de Xaringan lui-même  :

```{r eval=FALSE}
install.packages('xaringan')
```

Encore mieux, vous pouvez installer à la place le package permettant de faire des slides chartées Datactivist :

```{r eval=FALSE}
devtools::install_github("datactivist/slides_datactivist")
```

--

Au passage, vérifiez que votre R est à jour en regardant la version avec la fonction  : `R.version()`. La version la plus récente à date est la 3.6.1.

---

### Créer un nouveau projet

Dans le menu "File", sélectionnez *New project* et les options suivantes : New Directory / Empty project.

Vous serez alors invité·e·s à nommer le projet et choisir son emplacement :
* choisissez un emplacement pratique et logique (i.e. : que vous retrouverez facilement) ;
* donnez à votre projet un nom compact sans caractère spéciaux, accents ou espace (préférez les "-" et "_") ;
* cochez la case "Create a git repository", ça vous servira plus tard.

--

Vous devriez alors avoir dans votre dossier :
* **un fichier .Rproj** : qui contient les paramètres de votre projet ;
* **un fichier .gitignore** : dont nous parlerons plus tard.
* **un fichier .Rhistory** : qui apparaîtra dès que vous faîtes un truc et vous sert à garder l'historique des commandes utilisées.

---

### Créer un nouveau Rmd

Vous pouvez maintenant créer votre fichier source en R Markdown (abrégé Rmd) : dans le menu "File", sélectionnez *New file* puis *R Markdown*.

Ici, les options qui nous intéressent sont dans les templates : **"Ninja Presentation"** ou **"Slides Datactivist"** (le thème Xaringan *parfum Datactivist* concocté par Joël) permettront de créer le fichier source de notre présentation :

![](./img/rstudio_newfile_rmd.png)

---

### Le fichier source 1/2

Le fichier source est composé de plusieurs parties et écrit suivant une grammaire propre mais très simple.

Au tout début se trouve **le YAML**, codé dans [le langage du même nom](https://fr.wikipedia.org/wiki/YAML), qui paramètre le document.

C'est grâce au YAML que nous pourrons modifier l'entête mais aussi les pieds de page, appeler d'autres polices, etc. Il est délimité en haut et en bas par un triple dash bleu :

.center[![:largeur 60%](img/rmd-yaml.png)]

---

### Le fichier source 2/2

.center[![:largeur 80%](./img/rmd_markdown.png)]

Tout le reste du document est constitué par le contenu de la présentation format en Rmd, un format Markdown adapté à R.

Le texte est mis en forme avec du md, les contenus (images, liens hypertexte, gif et même cartes interactifs) insérés via des fonctions markdown ... tout se fait en texte !

Les slides sont délimités par des triples dash jaunes.

---

### Compiler votre présentation

Pour "voir" le résultat, vous devez *compiler* votre présentation. C'est-à-dire lancer le processus d'interprétation de votre fichier Rmd en fichier de présentation HTML. Pour cela, il vous suffit de cliquer sur le bouton **Knit** dans la barre supérieure de votre document.

Un aperçu apparaît à droite dans le "Viewer", où vous pouvez naviguer `r emo::ji("sunglasses")` :

.center[![:largeur 80%](./img/compile.png)]

---

background-image: url(https://media.giphy.com/media/CovFciJgWyxUs/giphy.gif)
class: center, top, inverse

# 2. Mettre sa présentation en forme

---

## La base : le markdown

Comme expliqué plus tôt, Xaringan est basé sur un document source en texte simple formaté en **Markdown**. Le markdown a de nombreux avantages :
* **lisible** : les "balises" md sont courtes et faciles à lire, ce qui permet de les ajouter et corriger rapidement. A fortiori avec la coloration syntaxique de Rstudio ou Sublime Text ;
* **compact** : la plupart des options consistent en une poignée de caractères. En dehors des graisses et itals, la plupart des "balises" n'ont pas besoin d'être fermées... Le texte mis en forme est donc aisément lisible même formaté ;
* **limitées** : le md offre des options limitées mais pratiques, ce qui évite de se perdre dans d'interminables cheatsheets.

L'intégalité des fonctions tient sur une page :
* Github propose [une intro](https://help.github.com/en/articles/basic-writing-and-formatting-syntax) et [un doc de référence](https://guides.github.com/features/mastering-markdown/) ;
* Yihui, auteur du package Xaringan, a fait un [bookdown](https://bookdown.org/) complet sur le sujet : "[A definitive guide](https://bookdown.org/yihui/rmarkdown)"

---

## Mise en forme du texte

La **mise en forme** du *texte* est ~~foutrement~~ __extrêmement__ simple puisqu'elle repose sur :
* une poignée de signe : *, _, #, ~ et > ;
* une syntaxe minimale ;
* une hiérarchie spatiale intuitive.

--

Le paragraphe ci-dessus a ainsi été écrit avec le texte suivant :
```
 La **mise en forme** du *texte* est ~~foutrement~~ __extrêmement__ simple puisqu'elle repose sur :
 * une poignée de signe : *, _, #, ~ et > ;
 * une syntaxe minimale ;
 * une hiérarchie spatiale intuitive.

```

Prenons les éléments un par un.

---

### Formater le texte simple

Le formatage simple fonctionne sur un principe de balise : des signes ajoutés avant et après le texte que l'ont souhaite modifier (comme du HTML mais en plus simple).

Les options disponibles sont les suivantes :
* pour mettre en *italique*, vous pouvez entourer l'expression soit d'étoiles `*comme ça*`, soit d'underscore simple `_ainsi_` ;
* pour mettre en **gras**, il faut doubler : deux étoiles `**comme ça**` ou deux underscore `__ainsi__` ;
* vous pouvez aussi ~~rayer~~ en utilisant des doubles tildes, `~~de cette manière~~` ;
* hélas, rien pour souligner.

.center[
### .red[Attention] `r emo::ji("warning")`
Le signe doit toucher le premier et le dernier signe de la chaîne de caractère. Si vous mettez un espace, cela ne fonctionnera pas (ou activera une autre fonction).
]

---

### La titraille et les listes

Les titres sont ajoutés via la balise "#" : chaque niveau de titre correspond à un nombre de #. Les balises titres se mettent en début de ligne et sont séparées du texte par un espace :

```
# Titre 1 : le·a boss des titres
## Titre 2 : le·a DG des titres
### Titre 3 : le·a chef·fe de service des titres
#### Titre 4 : le·a chef·fe d'équipe des titres
##### Titre 5 : l'intérimaire des titres.
```

Pour les listes, c'est le même principe : les listes non ordonnées sont initées en plaçant une "*" en début de ligne puis un espace (sinon, c'est un ital). Les listes ordonnées sont initiées en plaçant un chiffre suivant d'un point et d'un espace.

```
 * élément non ordonné
 * autre élément non ordonné

1. 1er élément
2. 2è élément.
```

---

background-image: url(https://media.giphy.com/media/8Hg2FpkTYkdJC/giphy.gif)
class: center, top, inverse

# Patience les chatons, ça arrive

---

### Ajouter du texte spécial

* liens hypertexte
* inline code
* blockcode
* [quote + quote footer](https://bookdown.org/yihui/rmarkdown/tufte-quotes.html)

---

## Mise en forme des slides

* couper les slides
* .position[]
* pull-left
* styling par page

---

## Bonus made in Datactivist

.red
.reduce

---

background-image: url(https://media.giphy.com/media/p668TRpM2r8bK/giphy.gif)
class: center, top, inverse

# 3. Ajouter du contenu

---

* images (via URL)
* fonctions R
* dataviz
* GIF

---

background-image: url(https://media.giphy.com/media/l4FGBILjNaCtLious/giphy.gif)
class: center, top, inverse

# 4. Rendre ses prezs réplicables

---

* organisation des fichiers
* templates
* variables

---

background-image: url(https://media.giphy.com/media/905GG7MjDw61q/giphy.gif)
class: center, top, inverse

# 5. GIT it to the next level

---

* rudiments GIT
* remote
* initial pull
* add / commit / push
* plus avancé

---

background-image: url(https://media.giphy.com/media/J3Ao5L98X8oms/giphy.gif)
class: center, top, inverse

# 6. Fonctionnalités avancées

---

* inline function

---

background-image: url(https://media.giphy.com/media/10vA3MTGTKeb16/giphy.gif)
class: center, top, inverse

# 7. Adapter et créer son propre thème

---

class: inverse, center, middle

# Merci !

Contact : [sylvain@datactivist.coop](mailto:sylvain@datactivist.coop)

**Comment by SylvainLapoix** [comment]
Merci Cécile !

Je vais reprendre tes suggestions. En revanche, il s'agissait pour moi d'une présentation généraliste plutôt qu'à usage interne, je pense retirer les mentions de Datactivist comme organisation.

**Comment by SylvainLapoix** [comment]
Pour les préalables R et Rstudio, je pense faire une prez spécifique.

J'ajouterai le lexique, ça me semble une très bonne idée !
